    <?xml version="1.0" encoding="UTF-8"?>
   <!DOCTYPE student [
<!ELEMENT student (name,roll,dob,address)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT roll (#PCDATA)>
<!ELEMENT dob (#PCDATA)>
<!ELEMENT address (#PCDATA)>
]>
<student>
    <name>James Jones</name>
    <roll>PACKT/1001/16</roll>
    <dob>17-01-1947</dob>
    <address>Birmingham, United Kingdom</address>
</student>